# Occupation

### Introduction:

Special thanks to: https://github.com/justmarkham for sharing the dataset and materials.

### Step 1. Import the necessary libraries

In [2]:
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user).

### Step 3. Assign it to a variable called users.

In [3]:
users = pd.read_csv("https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user",sep='|')

In [4]:
users.head(20)

    user_id  age gender     occupation zip_code
0         1   24      M     technician    85711
1         2   53      F          other    94043
2         3   23      M         writer    32067
3         4   24      M     technician    43537
4         5   33      F          other    15213
5         6   42      M      executive    98101
6         7   57      M  administrator    91344
7         8   36      M  administrator    05201
8         9   29      M        student    01002
9        10   53      M         lawyer    90703
10       11   39      F          other    30329
11       12   28      F          other    06405
12       13   47      M       educator    29206
13       14   45      M      scientist    55106
14       15   49      F       educator    97301
15       16   21      M  entertainment    10309
16       17   30      M     programmer    06355
17       18   35      F          other    37212
18       19   40      M      librarian    02138
19       20   42      F      homemaker    95660

### Step 4. Discover what is the mean age per occupation

In [5]:
users[['age','occupation']].groupby(by=users['occupation']).mean()

                     age
occupation
administrator  38.746835
artist         31.392857
doctor         43.571429
educator       42.010526
engineer       36.388060
entertainment  29.222222
executive      38.718750
healthcare     41.562500
homemaker      32.571429
lawyer         36.750000
librarian      40.000000
marketing      37.615385
none           26.555556
other          34.523810
programmer     33.121212
retired        63.071429
salesman       35.666667
scientist      35.548387
student        22.081633
technician     33.148148
writer         36.311111

### Step 5. Discover the Male ratio per occupation and sort it from the most to the least

In [86]:
male = users.groupby(['occupation','gender']).size().unstack(fill_value=0)
male['total'] = male.sum(axis=1)
male['male-ratio'] = (male['M']/male['total']).round(2)
male['male-ratio'].sort_values(ascending=False)

occupation
doctor           1.00
engineer         0.97
technician       0.96
retired          0.93
executive        0.91
programmer       0.91
scientist        0.90
entertainment    0.89
lawyer           0.83
salesman         0.75
educator         0.73
student          0.69
other            0.66
marketing        0.62
writer           0.58
none             0.56
administrator    0.54
artist           0.54
librarian        0.43
healthcare       0.31
homemaker        0.14
Name: male-ratio, dtype: float64

### Step 6. For each occupation, calculate the minimum and maximum ages

In [7]:
users[['age','occupation']].groupby(by=users['occupation']).agg(['min','max'])

              age
              min max
occupation
administrator  21  70
artist         19  48
doctor         28  64
educator       23  63
engineer       22  70
entertainment  15  50
executive      22  69
healthcare     22  62
homemaker      20  50
lawyer         21  53
librarian      23  69
marketing      24  55
none           11  55
other          13  64
programmer     20  63
retired        51  73
salesman       18  66
scientist      23  55
student         7  42
technician     21  55
writer         18  60

### Step 7. For each combination of occupation and gender, calculate the mean age

In [41]:
users.groupby(['occupation','gender'],as_index=False)[['occupation','gender','age']].agg({'age':'mean'})

       occupation gender        age
0   administrator      F  40.638889
1   administrator      M  37.162791
2          artist      F  30.307692
3          artist      M  32.333333
4          doctor      M  43.571429
5        educator      F  39.115385
6        educator      M  43.101449
7        engineer      F  29.500000
8        engineer      M  36.600000
9   entertainment      F  31.000000
10  entertainment      M  29.000000
11      executive      F  44.000000
12      executive      M  38.172414
13     healthcare      F  39.818182
14     healthcare      M  45.400000
15      homemaker      F  34.166667
16      homemaker      M  23.000000
17         lawyer      F  39.500000
18         lawyer      M  36.200000
19      librarian      F  40.000000
20      librarian      M  40.000000
21      marketing      F  37.200000
22      marketing      M  37.875000
23           none      F  36.500000
24           none      M  18.600000
25          other      F  35.472222
26          other      M  34.028986
27     programmer      F  32.166667
28     programmer      M  33.216667
29        retired      F  70.000000
30        retired      M  62.538462
31       salesman      F  27.000000
32       salesman      M  38.555556
33      scientist      F  28.333333
34      scientist      M  36.321429
35        student      F  20.750000
36        student      M  22.669118
37     technician      F  38.000000
38     technician      M  32.961538
39         writer      F  37.631579
40         writer      M  35.346154

### Step 8.  For each occupation present the percentage of women and men

In [ ]:
cou = users.groupby(['occupation','gender']).size().unstack(fill_value=0)
cou['Total'] = cou.sum(axis=1)
cou['fem-perc'] = ((cou['F']/cou['Total'])*100).round(2)
cou['male-perc'] = ((cou['M']/cou['Total'])*100).round(2)
cou[['fem-perc','male-perc']]

gender         fem-perc  male-perc
occupation
administrator     45.57      54.43
artist            46.43      53.57
doctor             0.00     100.00
educator          27.37      72.63
engineer           2.99      97.01
entertainment     11.11      88.89
executive          9.38      90.62
healthcare        68.75      31.25
homemaker         85.71      14.29
lawyer            16.67      83.33
librarian         56.86      43.14
marketing         38.46      61.54
none              44.44      55.56
other             34.29      65.71
programmer         9.09      90.91
retired            7.14      92.86
salesman          25.00      75.00
scientist          9.68      90.32
student           30.61      69.39
technician         3.70      96.30
writer            42.22      57.78